name: 'opa'
description: 'Run OPA test command'
inputs:
  path:
    description: 'Path to directory where rego files are located'
    required: false
    default: '.'
  coverage:
    description: 'Percentage of test coverage to require'
    required: false
    default: '80%'
  files:
    description: 'Files subject to OPA testing. List should be separated by a space'
    required: false
    default: ''
outputs:
  result:
    description: 'Outputs of OPA command'
runs:
  using: 'docker'
  image: 'Dockerfile'
